### ISSUE TITLE
Exporting footage as a single mp4 file

### ISSUE THREAD

**Issue by piedoom** [scottlamb/moonfire-nvr#127]
I looked through this bit of the [schema.md](https://github.com/scottlamb/moonfire-nvr/blob/0c34ea8314eb1487b9f9117af047dc80aaf2712e/design/schema.md#duration-of-recordings). The link labeled "below" seems broken, I think maybe it should link [here](https://github.com/scottlamb/moonfire-nvr/blob/0c34ea8314eb1487b9f9117af047dc80aaf2712e/design/schema.md#on-demand)? 

That file mentioned exporting, so I am wondering if Moonfire has a way to export footage to a single file - and if not - if that is something within the scope of this project. Thanks!

edit: I see that setting max duration to infinite basically does this, so closing.

(Omitted N/A fields)

**Comment by scottlamb** [comment]
I'll fix the anchor link; thanks for pointing it out.

> edit: I see that setting max duration to infinite basically does this, so closing.

Yeah, with that option the UI will let you make a single `.mp4` file that is arbitrarily long. It has to be a contiguous stream of recording—no disconnects. And it has to be the same camera. Those are UI limitations; within the code, `mp4::FileBuilder` will let you splice together your whole database.
