### ISSUE TITLE
zero-dependencies Linux binary

### ISSUE THREAD

**Issue by scottlamb** [scottlamb/moonfire-nvr#160]
I think it's possible to produce a `moonfire-nvr` Linux binary that has no dependencies except tzdata and any remotely recent version of glibc. (Or we could try going absolutely statically linked with musl, but then we might also need to bring in jemalloc for decent performance, etc.)

We'd likely still use Docker for the build but have install instructions that don't require either Docker or compilation.

*   [ ] Build in a docker environment that has a suitable old glibc to link against. see eg https://kobzol.github.io/rust/ci/2021/05/07/building-rust-binaries-in-ci-that-work-with-older-glibc.html
*   [x] Stop using ffmpeg entirely. (#37  Retina is working for me but we should work out some more camera compatibility problems before removing ffmpeg.)
*   [ ] Avoid ncurses, either by completing the web interface (#35) or by using an alternate cursive backend (some success with this at #149)
*   [ ] Likely compile the UI into the binary, although continue to support `--ui-dir` for development.
*   [ ] Update release procedure to create binaries on GitHub release instead of / in addition to Docker images.

Caveat: on-NVR analytics support will likely be a separate binary that *won't* be so easy to make zero-dependency. We need to continue using ffmpeg or some other library for H.264 decoding, we'll likely depend on TensorFlow Lite, etc. But I think there's still value anyway in having the core system be super easy to install. Docker is its own pile of complexity for users to deal with.

**Comment by IronOxidizer** [comment]
> Build in a docker environment that has a suitable old glibc to link against

Would static linking against MUSL libc be an option here?
