### ISSUE TITLE
Implement CORS policy

### ISSUE THREAD

**Issue by dolfs** [scottlamb/moonfire-nvr#17]
In order to allow UI development from a system that is not the moonfire-nvr server itself CORS headers would need to be added as appropriately. Sample code for this can be found [here](https://github.com/SergioBenitez/Rocket/issues/25) in one of the later comments.

At this time it might make sense to simply allow origin "any" or (* in the header) since the API is unsecured anyway. In future we may need to think about this more.

Without this support, running the ui code from, let's say localhost:3000 will not allow API access and, effectively, makes development hard. It is possible, in Safari for example, to disable cross domain policy enforcement through the develop menu, but that disables it across the board, which is rather unsafe if you forget to put it back, or browse dangerous sites in the meanwhile.

**Comment by scottlamb** [comment]
How about we add a flag `--api-access-control-allow-origin` which sets the `Access-Control-Allow-Origin` header to the given value on all HTTP responses to `/api/` requests? That seems easy enough to do. The default would be to not set the header (the current behavior).

fwiw, another approach is for whatever other system you're doing development with to proxy the `/api/` requests. in Apache for example this is pretty easy:

```
ProxyPass "/api" "http://odroid:8080/api"
```

**Comment by dolfs** [comment]
I guess the flag would work. I’ll keep in mind the proxy approach. Have to see how that works in the dev setup I am working on.
Dolf Starreveld                  	
email <mailto:registration@starreveld.com>

**Comment by scottlamb** [comment]
Does #19 work for you?

**Comment by dolfs** [comment]
I’m going to have to install the latest from master first… Will let you know.
Dolf Starreveld                  	
email <mailto:registration@starreveld.com>

**Comment by dolfs** [comment]
Yes, tested it and it works.
Dolf Starreveld                  	
email <mailto:registration@starreveld.com>
