### ISSUE TITLE
Calling API with invalid arg causes connection reset

### ISSUE THREAD

**Issue by dolfs** [scottlamb/moonfire-nvr#20]
I happened to be doing UI development using a proxy to a normally running moonfire instance. Due to coding error the API for recordings was called with start and end time set to null. Rather then producing an appropriate HTTP response (may be 500, or even 404) would have been expected.

Needless to say that the connection reset causes error messages that are unwanted, but it also means API calling code does not get its error path executed.

Sample output:
```
[HPM] Error occurred while trying to proxy request /api/cameras/1c844181-b807-4b80-83eb-579c8e194451/recordings?startTime90k=null&endTime90k=null&split90k=324000000&_=1520229643233 from localhost:3000 to http://192.168.10.232:8080 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

**Comment by dolfs** [comment]
This was against running code from commit 8de7e391f8cd754cf205e737cf47b19ceb7012b4 so it is possible this has already been fixed. No time at the moment to upgrade running version.

**Comment by scottlamb** [comment]
It hasn't been fixed. At present, almost any problem will cause it to just drop the connection rather than return a proper HTTP error. It should at least log something to console that will likely tell you what went wrong.
