### ISSUE TITLE
[Suggestion] Evaluate F2FS as root filesystem to increase flash endurance

### ISSUE THREAD

**Issue by IronOxidizer** [scottlamb/moonfire-nvr#212]
F2FS is notable for being designed from the ground up to maximize flash endurance and performance. It might be worth evaluating and mentioning it in the docs for anyone who wants to go the extra mile considering the amount of effort already put into the configuration (via docs) and implementation of moonfire-nvr to increase drive endurance.

**Comment by scottlamb** [comment]
That'd fit in well in the wiki here: https://github.com/scottlamb/moonfire-nvr/wiki/System-setup#configuring-filesystems

**Comment by IronOxidizer** [comment]
Added a small bullet point for it
