### ISSUE TITLE
Enhancement: add "start" alias for run

### ISSUE THREAD

**Issue by jlpoolen** [scottlamb/moonfire-nvr#215]
The current alias to commence moonfire-nvr is "run".  I work a great deal with services where the most often terms are used are "start", "stop" -- though, in this case, running moonfire-nvr from a console does not need at "stop".  Could an alias of "start" be added, I'm constantly entering "nvr start" only to have to see that I should be using "run".

**Comment by scottlamb** [comment]
I just (in ee98bf5236ce9f09666c4317defbe7ad4297412b) killed the Docker setup and the `nvr` wrapper script, so now:

* `sudo -u moonfire-nvr moonfire-nvr run` will not only start Moonfire but also directly run it until you hit ctrl-C or the like. I don't think the name `start` would be clear about this.
* When set up with systemd, `sudo systemctl start moonfire-nvr` will start it (and return immediately)
* or `sudo systemctl enable --now moonfire-nvr` will enable it to start on boot and start it now
