### ISSUE TITLE
stream test failed

### ISSUE THREAD

**Issue by maomj200811** [scottlamb/moonfire-nvr#298]
**Describe the bug**
A clear and concise description of the problem.

the following question is : DESCRIBE Cseq=1: Describe response not of expected application/sdp content type: Response

![image](https://github.com/scottlamb/moonfire-nvr/assets/156042868/fc054a66-5a7c-4a85-9dbf-2733afce3d5b)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
  - `moonfire-nvr --version`
  - Attach a [log file](https://github.com/scottlamb/moonfire-nvr/blob/master/guide/troubleshooting.md#viewing-moonfire-nvrs-logs). Run with the `RUST_BACKTRACE=1` environment variable set if possible.

**Camera (please complete the following information):**
  - Camera manufacturer and model: [e.g. Reolink RLC-410]
  - Firmware version: [e.g. `V2.0.0.1215_16091800`]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by maomj200811** [comment]
version v0.7.11

**Comment by scottlamb** [comment]
What camera manufacturer/model/version is this?

The response is supposed to include `Content-Type: application/sdp` and doesn't but otherwise looks plausible. I can probably just have Retina (Moonfire's protocol layer) assume that content type if none is specified.

**Comment by maomj200811** [comment]
but this video can play normally using vlc player, video source is published using ffmpeg

**Comment by maomj200811** [comment]
but this video can play normally using vlc player, video source is published using ffmpeg

**Comment by scottlamb** [comment]
VLC is pretty forgiving. Moonfire can be too; I'll release an updated version shortly that should work better.

**Comment by scottlamb** [comment]
v0.7.12 *should* be out shortly...but Github Actions seems to be in a bad mood, so we'll see.

**Comment by maomj200811** [comment]
> VLC is pretty forgiving. Moonfire can be too; I'll release an updated version shortly that should work better.

what time it will updated newest version?

**Comment by scottlamb** [comment]
When [this action](https://github.com/scottlamb/moonfire-nvr/actions/runs/7457036703) completes...so right now! Please give it a try.

**Comment by maomj200811** [comment]
thanks. a lot it's ok now..  but now I has new questions  about moonfire-nvr, my camera record storage is zero size. the following.

![image](https://github.com/scottlamb/moonfire-nvr/assets/156042868/be883b36-68e2-473f-9573-fe0d193cc8db)

**Comment by scottlamb** [comment]
Yeah, that's definitely not right. There are likely clues in the logs.

**Comment by scottlamb** [comment]
I see you opened #300 for that; closing this issue out.
