### ISSUE TITLE
why my saved video length 15s only, flush_if_second is config 120s or more time

### ISSUE THREAD

**Issue by maomj200811** [scottlamb/moonfire-nvr#301]
**Describe the bug**
A clear and concise description of the problem.

<img width="1440" alt="截屏2024-01-13 14 43 23" src="https://github.com/scottlamb/moonfire-nvr/assets/156042868/94ef1dc4-3f78-4e42-a46d-4c31550aa977">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
  - `moonfire-nvr --version`
  - Attach a [log file](https://github.com/scottlamb/moonfire-nvr/blob/master/guide/troubleshooting.md#viewing-moonfire-nvrs-logs). Run with the `RUST_BACKTRACE=1` environment variable set if possible.

**Camera (please complete the following information):**
  - Camera manufacturer and model: [e.g. Reolink RLC-410]
  - Firmware version: [e.g. `V2.0.0.1215_16091800`]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by scottlamb** [comment]
I suspect this is the same root cause as #300. But there's no information here; the screenshot is not helpful. The other stuff in the issue template such as logs and details of the cameras being recorded are really needed to understand what's going on.
