### ISSUE TITLE
添加更多时间选项-Add more time options

### ISSUE THREAD

**Issue by mung6lung4** [scottlamb/moonfire-nvr#321]
![捕获](https://github.com/scottlamb/moonfire-nvr/assets/53356318/460bb933-f723-436a-a877-e5a34bab3fab)
![捕获2](https://github.com/scottlamb/moonfire-nvr/assets/53356318/81c9c0ab-3e2f-4988-b0d9-9e0ea5016ad6)
-------------------------------------------------------------------------------------------------
我希望在下一个新版本更新这些并打包至二进制文件，我会更新的。这样修改使得时间有更多选择，只需轻松修改js文件即可。
I hope to update these and package them into binaries in the next new version, I will update. This modification allows you to have more choices, just modify the js file easily.

**Comment by zaumal** [comment]
你好，请教个问题，我通过docker方式部署成功后，只能保留最近的几分钟的视频，其他时间的都会被自动删除，请问如何配置才能保留所有的视频。
![image](https://github.com/user-attachments/assets/4d10d057-4dea-49f9-85e3-6e3e36f80c9e)
